services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - SERVER_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quotes_network

  db:
    image: postgres:15-alpine
    container_name: postgres_database
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USERNAME} -d $${POSTGRES_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quotes_network

networks:
  quotes_network:
    driver: bridge

volumes:
  postgres_data: